### ISSUE TITLE
Ich möchte Herrn Wolf als Abteilungsleiter Geschäftsführer entfernen, wie geht dass? 

### ISSUE THREAD

**Issue by sascha210474** [timvallandi/abrechnung.flvw.app#12]
**Um welche Art von Problem handelt es sich?**
Technisch oder Inhaltlich (z.B. Frage zu einem Finanz-Thema)

**Welches Problem hast du bei der Bedienung der App?**
Peter Wolf sieht in der App wenn Abrechnungen für die Abteilung Geschäftsführer eingehen und kann diese auch freigeben. Dieses Recht will ich ihm entziehen. Wo kann ich das?

**Was hast du schon versucht, um das Problem zu lösen?**
Eine klare und präzise Beschreibung, was du schon alles probiert hast.

**Weitere Informationen**
Ein Link von der Seite auf der Du ein Problem hast, Screenshots und andere Infos helfen sehr dabei, dein Problem schnellstmöglich zu lösen.

**Comment by timvallandi** [comment]
Gehe in die Benutzer-Verwaltung und suche dort den entsprechenden Benutzer. 

Namen anklicken und es öffnet sich ein Fenster in dem Du unter anderem die Rollen auswählen kannst. 
Bei Klick auf Rollen kannst du die verfügbaren Rollen setzen. 
Hier müsstest du nun den Haken bei "Abteilungsleiter" entfernen und danach dann das Fenster schließen.

**Comment by sascha210474** [comment]
Ok, wenn ich Abteilungsleiter stehen lasse, sieht er dann alle Abteilungen. Sprich auch wenn jemand eine Abrechnung an die Abteilung fussballjugend schickt? Oder gibt es eine bestimme Beziehung zwischen Peter Wolf und der Abteilung Geschäftsführer.


Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by timvallandi** [comment]
Mit Umsetzung von Feature #7 würdest du die Abteilung ändern bzw. löschen können. 

Derzeit kannst du dann nur die komplette Rolle entfernen und Herr Wolf sieht dann gar keine Abrechnungen auf Abteilungssicht mehr. 

Alternativ können wir auch erstmal mit einer "Testabteilung" arbeiten analog zum "Testkreis".
Die Zuordnung könnte bis zur Veröffentlichung der neuen Version allerdings nur von mir gemacht werden.

**Comment by sascha210474** [comment]
Ist es ok, wenn wir dies morgen einmal telefonisch klären?

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
